-- Seed: content library — initial content items per industry
-- Run AFTER migration 20260726000001_create_content_library.sql
-- 3 items per industry (7 industries × 3 = 21 items)
-- Images will be generated by the daily cron job
-- Created: 2026-07-26

DO $$
DECLARE
  ind_inmob   UUID := (SELECT id FROM kefy_content_industries WHERE slug = 'inmobiliario');
  ind_eventos UUID := (SELECT id FROM kefy_content_industries WHERE slug = 'eventos');
  ind_b2b     UUID := (SELECT id FROM kefy_content_industries WHERE slug = 'b2b_saas');
  ind_ecomm   UUID := (SELECT id FROM kefy_content_industries WHERE slug = 'ecommerce');
  ind_edu     UUID := (SELECT id FROM kefy_content_industries WHERE slug = 'educacion');
  ind_gastro  UUID := (SELECT id FROM kefy_content_industries WHERE slug = 'gastronomia');
  ind_salud   UUID := (SELECT id FROM kefy_content_industries WHERE slug = 'salud');
BEGIN

  -- ── Inmobiliario (Real Estate) ────────────────────────────────────────────────

  INSERT INTO kefy_content_library (industry_id, content_type, title, body, hashtags, image_prompt, source, language) VALUES
  (ind_inmob, 'post',
   '5 errores al buscar departamento',
   'Buscar depa nuevo puede ser estresante. Estos son los 5 errores más comunes que vemos en nuestros clientes:

1. No definir presupuesto antes de visitar
2. Ignorar los gastos comunes
3. No revisar la orientación del sol
4. Firmar sin leer la letra chica
5. No investigar el barrio de noche

¿Cuál de estos has cometido? Cuéntanos en los comentarios.

[Agenda una asesoría gratuita]',
   ARRAY['#inmobiliaria', '#departamentos', '#bienesraices', '#arriendos', '#tipshogar'],
   'Modern apartment building exterior at golden hour, warm sunlight reflecting off glass windows, urban residential neighborhood, photorealistic architectural photography',
   'seed', 'es'),

  (ind_inmob, 'carousel',
   'Checklist antes de firmar un arriendo',
   'Antes de firmar tu contrato de arriendo, asegúrate de revisar cada uno de estos puntos. Un error puede costarte meses de problemas.

Slide 1: Verifica el estado del inmueble con fotos
Slide 2: Lee todas las cláusulas de término anticipado
Slide 3: Confirma quién paga las reparaciones
Slide 4: Revisa el monto exacto de gastos comunes
Slide 5: Pide referencias del arrendador

[Descarga nuestra checklist completa]',
   ARRAY['#arriendo', '#contrato', '#inmobiliaria', '#checklist', '#hogar'],
   'Clean modern living room with natural light, minimalist furniture, real estate staging photography, bright and airy interior',
   'seed', 'es'),

  (ind_inmob, 'reel',
   'Tour virtual: así se ve un depa bien publicado',
   '¿Quieres que tu propiedad se arriende rápido? La clave está en cómo la presentas.

En este video te mostramos la diferencia entre una publicación promedio y una que genera 10x más consultas.

Iluminación, ángulos, descripción y fotos profesionales hacen TODA la diferencia.

[Cotiza tu sesión de fotos profesionales]',
   ARRAY['#tourvirtual', '#propiedades', '#fotoinmobiliaria', '#arriendos', '#realestate'],
   'Professional real estate photographer taking photos of a bright modern apartment, camera on tripod, natural lighting streaming through large windows',
   'seed', 'es');

  -- ── Eventos y Ticketeras ──────────────────────────────────────────────────────

  INSERT INTO kefy_content_library (industry_id, content_type, title, body, hashtags, image_prompt, source, language) VALUES
  (ind_eventos, 'post',
   'Cómo llenar un evento sin gastar en ads',
   'No siempre necesitas presupuesto en publicidad para llenar tu evento. Estas 4 estrategias orgánicas funcionan mejor de lo que crees:

→ Crea un grupo exclusivo de "early birds" en WhatsApp
→ Pide a tus speakers que compartan con su audiencia
→ Ofrece un descuento por referidos (2x1 si traes a alguien)
→ Publica contenido detrás de escenas en Stories

¿Cuál vas a probar primero?

[Registra tu evento con nosotros]',
   ARRAY['#eventos', '#marketing', '#ticketing', '#eventplanning', '#estrategia'],
   'Crowded concert venue with colorful stage lights, enthusiastic audience with raised hands, live music event atmosphere, professional event photography',
   'seed', 'es'),

  (ind_eventos, 'post',
   'El error #1 de los organizadores de eventos',
   'El error más caro que puedes cometer como organizador: no tener un plan B para el clima.

Lluvia, calor extremo o viento pueden arruinar meses de planificación. ¿La solución?

✓ Siempre ten un venue alternativo bajo techo
✓ Comunica el plan B en la invitación
✓ Ten un kit de emergencia (carpas, ventiladores, calefacción)

La diferencia entre un evento memorable y un desastre está en la preparación.

[Consulta nuestro servicio de producción]',
   ARRAY['#organizadoreventos', '#eventplanner', '#produccion', '#tips', '#eventos'],
   'Outdoor event setup with elegant white tent and string lights, sunset sky in background, professional catering tables arranged underneath, event planning photography',
   'seed', 'es'),

  (ind_eventos, 'carousel',
   'Timeline ideal para organizar un evento',
   '¿Cuánto tiempo antes deberías empezar a planificar? Te dejamos el timeline perfecto:

6 meses antes: Define objetivo, presupuesto y venue
4 meses antes: Confirma speakers y proveedores clave
2 meses antes: Lanza venta de tickets y campaña de difusión
1 mes antes: Confirma logística, catering y equipos técnicos
1 semana antes: Ensayo general y coordinación final

[Agenda una llamada de planificación]',
   ARRAY['#eventplanning', '#timeline', '#organizacion', '#eventos', '#produccion'],
   'Professional event planner working at a desk with timeline charts, mood boards and fabric swatches, organized workspace with laptop, creative planning atmosphere',
   'seed', 'es');

  -- ── B2B / Consultoría / SaaS ──────────────────────────────────────────────────

  INSERT INTO kefy_content_library (industry_id, content_type, title, body, hashtags, image_prompt, source, language) VALUES
  (ind_b2b, 'post',
   'Por qué tus demos no convierten',
   'Haces 20 demos al mes pero cierras 2. ¿Te suena?

El problema no es tu producto. Es tu demo.

La mayoría de los vendedores B2B cometen el mismo error: mostrar features en vez de resolver el dolor del cliente.

Cambia "mira lo que puede hacer" por "así resolvemos tu problema de [X]" y verás la diferencia.

El demo perfecto dura 20 minutos, no 45.

[Agenda una consultoría de ventas B2B]',
   ARRAY['#b2b', '#ventas', '#saas', '#demos', '#consultoria'],
   'Modern glass office meeting room with two professionals in a business meeting, laptop showing software dashboard, clean corporate interior, natural lighting',
   'seed', 'es'),

  (ind_b2b, 'carousel',
   'Métricas SaaS que deberías trackear',
   'Si manejas un SaaS y solo miras MRR, estás volando a ciegas.

Estas 5 métricas te dicen la verdad sobre tu negocio:

1. MRR + Net Revenue Retention
2. CAC Payback Period
3. Logo Churn vs Revenue Churn
4. Time to Value (TTV)
5. NPS por segmento de cliente

¿Cuáles trackeas hoy?

[Descarga nuestra plantilla de métricas]',
   ARRAY['#saas', '#metricas', '#startup', '#b2b', '#analytics'],
   'Clean data dashboard on a large monitor screen showing charts and graphs in blue tones, modern tech office desk setup, analytics visualization, professional workspace',
   'seed', 'es'),

  (ind_b2b, 'post',
   'Cómo escribir emails fríos que sí abren',
   'El 90% de los cold emails terminan en la basura. Pero hay una fórmula que funciona:

Asunto: Pregunta específica sobre su empresa (no "Propuesta comercial")
Línea 1: Algo que investigaste sobre ELLOS
Línea 2: El problema que probablemente tienen
Línea 3: Cómo lo resolviste para alguien similar
CTA: Una pregunta simple, no un link

Respuesta promedio: 23% vs 3% del email genérico.

[Pide nuestra guía de cold outreach]',
   ARRAY['#coldemail', '#outreach', '#b2bsales', '#prospecting', '#ventas'],
   'Close-up of hands typing on a laptop keyboard, email inbox visible on screen, modern minimalist desk with coffee cup, warm office lighting, professional productivity',
   'seed', 'es');

  -- ── eCommerce / Retail ────────────────────────────────────────────────────────

  INSERT INTO kefy_content_library (industry_id, content_type, title, body, hashtags, image_prompt, source, language) VALUES
  (ind_ecomm, 'post',
   'El truco de las fotos de producto que venden',
   '¿Sabías que el 75% de los compradores online decide por la foto?

No necesitas un estudio profesional. Con tu celular y estos tips:

→ Usa luz natural (cerca de una ventana)
→ Fondo blanco o neutro (una cartulina sirve)
→ Muestra el producto en contexto (alguien usándolo)
→ Toma mínimo 5 ángulos diferentes
→ Edita brillo y contraste (Snapseed es gratis)

La diferencia entre "nadie compra" y "agotado" muchas veces es solo la foto.

[Visita nuestra tienda]',
   ARRAY['#ecommerce', '#fotoproducto', '#tiendaonline', '#ventas', '#marketing'],
   'Flat lay product photography setup with natural light from window, white background, smartphone on mini tripod, small products artfully arranged, lifestyle photography',
   'seed', 'es'),

  (ind_ecomm, 'post',
   '3 emails que toda tienda online necesita',
   'Si tu tienda online no envía estos 3 emails automáticos, estás perdiendo ventas:

1. Carrito abandonado (enviar a las 2 horas) — recupera un 15-20% de ventas perdidas

2. Post-compra (enviar al día siguiente) — pide una reseña y sugiere productos complementarios

3. Reactivación (enviar a los 30 días sin compra) — ofrece un descuento exclusivo

Automatizar estos 3 flujos puede aumentar tus ventas un 25% sin gastar en ads.

[Configura tus automatizaciones]',
   ARRAY['#emailmarketing', '#ecommerce', '#automatizacion', '#tiendaonline', '#ventas'],
   'Laptop screen showing email marketing dashboard with automation flow chart, e-commerce workspace with packages and shipping supplies nearby, organized desk',
   'seed', 'es'),

  (ind_ecomm, 'reel',
   'Unboxing que enamora: cómo empacar tus pedidos',
   'El unboxing es el primer contacto físico con tu marca. Hazlo memorable.

En este video te mostramos paso a paso cómo crear una experiencia de unboxing que tus clientes querrán compartir en redes:

→ Caja con tu logo (o sticker personalizado)
→ Papel de seda del color de tu marca
→ Tarjeta de agradecimiento escrita a mano
→ Un regalo sorpresa pequeño
→ Instrucciones de cuidado del producto

Costo extra: menos de $1 por pedido. Impacto: clientes que vuelven.

[Compra en nuestra tienda]',
   ARRAY['#unboxing', '#packaging', '#ecommerce', '#experienciadecliente', '#branding'],
   'Beautiful product unboxing scene with branded tissue paper, thank you card, small gift, and product in elegant packaging, overhead shot, warm lighting, lifestyle photography',
   'seed', 'es');

  -- ── Educación / Cursos / Coaches ──────────────────────────────────────────────

  INSERT INTO kefy_content_library (industry_id, content_type, title, body, hashtags, image_prompt, source, language) VALUES
  (ind_edu, 'post',
   'Por qué tu curso online no vende (y cómo arreglarlo)',
   'Creaste un curso increíble pero nadie lo compra. ¿Por qué?

Porque estás vendiendo el curso, no la transformación.

Nadie quiere "12 módulos de marketing digital". Quieren "conseguir tus primeros 10 clientes en 30 días".

Cambia tu copy de features a resultados:
✗ "Acceso a 40 videos"
✓ "Domina Instagram en 4 semanas"

El contenido puede ser el mismo. La promesa lo cambia todo.

[Inscríbete a nuestro programa]',
   ARRAY['#cursosonline', '#infoproductos', '#coaching', '#educacion', '#marketing'],
   'Person studying at a clean modern desk with laptop showing online course platform, notebooks and highlighters, cozy home office with plants, warm ambient lighting',
   'seed', 'es'),

  (ind_edu, 'carousel',
   '5 tipos de contenido gratuito que venden cursos',
   'El contenido gratuito no "regala" tu conocimiento — genera confianza. Estos 5 formatos convierten:

1. Mini-tutorial que resuelve UN problema específico
2. Caso de estudio de un alumno con resultados
3. Mito vs Realidad de tu industria
4. Checklist descargable (a cambio del email)
5. Live Q&A semanal de 15 minutos

La clave: da el QUÉ gratis, cobra por el CÓMO detallado.

[Descarga nuestra guía de lanzamiento]',
   ARRAY['#contenidoeducativo', '#cursos', '#coaching', '#infoproductos', '#estrategia'],
   'Creative educator recording a video tutorial at their desk, ring light illuminating their face, camera on tripod, colorful background with educational posters, content creation setup',
   'seed', 'es'),

  (ind_edu, 'post',
   'Cómo cobrar lo que vale tu conocimiento',
   'Si cobras $50 USD por una sesión de coaching de 1 hora, estás regalando tu experiencia.

Esto es lo que realmente incluye esa hora:
→ 10 años de experiencia en tu campo
→ 3 horas de preparación previa
→ Seguimiento post-sesión
→ Herramientas y recursos personalizados

No cobras por tu tiempo. Cobras por la transformación que generas.

¿Cómo calcular tu tarifa real? Toma el resultado que entregas y ponle un precio proporcional al valor.

[Agenda una sesión de mentoría]',
   ARRAY['#coaching', '#precios', '#mentorias', '#emprendimiento', '#valorprofesional'],
   'Confident professional coach in a modern office having a mentoring session, warm and inviting atmosphere, two people in conversation, bookshelf in background',
   'seed', 'es');

  -- ── Gastronomía / Restaurantes ────────────────────────────────────────────────

  INSERT INTO kefy_content_library (industry_id, content_type, title, body, hashtags, image_prompt, source, language) VALUES
  (ind_gastro, 'post',
   'La foto de tu plato no vende. Esto sí.',
   '¿Tu comida es increíble pero las fotos no le hacen justicia?

El secreto no es una cámara cara. Es la historia que cuentas.

En vez de: "Nuevo plato disponible"
Prueba: "Este risotto lleva 45 minutos de cocción lenta con caldo hecho en casa desde las 6 AM"

La gente no compra comida. Compra la experiencia, la dedicación, el amor detrás del plato.

Muestra el proceso, no solo el resultado.

[Reserva tu mesa]',
   ARRAY['#gastronomia', '#restaurantes', '#foodie', '#marketingrestaurantes', '#comida'],
   'Beautifully plated gourmet dish on a rustic wooden table, steam rising, professional food photography with shallow depth of field, warm restaurant ambiance',
   'seed', 'es'),

  (ind_gastro, 'reel',
   'Detrás de cocina: un día con nuestro chef',
   'Los videos de "behind the scenes" en cocina generan 3x más engagement que las fotos de platos.

¿Por qué? Porque la gente quiere ver:
→ Las manos del chef trabajando
→ Los ingredientes frescos llegando
→ El fuego, el humo, los sonidos
→ La concentración y pasión del equipo

Un reel de 30 segundos mostrando tu cocina en acción vale más que 10 fotos perfectas del plato terminado.

[Síguenos para más contenido gastronómico]',
   ARRAY['#behindthescenes', '#cocina', '#chef', '#foodcontent', '#restaurante'],
   'Professional kitchen in action during dinner service, chef plating a dish with precise movements, flames in background, dynamic cooking scene with motion blur, restaurant kitchen photography',
   'seed', 'es'),

  (ind_gastro, 'post',
   'Cómo conseguir reseñas en Google sin rogar',
   'Las reseñas en Google son el marketing más poderoso para un restaurante. Pero pedirlas es incómodo.

La solución: hazlo fácil y natural.

1. Pon un QR en la cuenta que lleve directo a tu perfil de Google
2. Ofrece un café o postre gratis por la reseña (sí, está permitido)
3. Responde TODAS las reseñas — buenas y malas
4. Comparte las mejores reseñas en tus Stories

Restaurantes con +50 reseñas reciben 35% más reservas.

[Visítanos y deja tu opinión]',
   ARRAY['#reseñas', '#googlereviews', '#restaurante', '#marketinggastro', '#pymes'],
   'Happy customers dining at a cozy restaurant, warm ambient lighting, wine glasses on table, authentic dining experience, candlelight dinner scene',
   'seed', 'es');

  -- ── Salud / Wellness / Fitness ────────────────────────────────────────────────

  INSERT INTO kefy_content_library (industry_id, content_type, title, body, hashtags, image_prompt, source, language) VALUES
  (ind_salud, 'post',
   'El mito del "no tengo tiempo para hacer ejercicio"',
   'No necesitas 1 hora en el gimnasio para estar saludable.

La ciencia dice que 20 minutos de ejercicio de intensidad moderada, 3 veces por semana, ya genera beneficios reales:

→ Reduce el riesgo cardiovascular un 30%
→ Mejora la calidad del sueño
→ Reduce ansiedad y estrés
→ Aumenta la energía durante el día

20 minutos. No 60. No 90. Veinte.

¿Cuál es tu excusa favorita? Cuéntanos abajo.

[Agenda tu primera clase gratis]',
   ARRAY['#fitness', '#ejercicio', '#saludmental', '#bienestar', '#vidasaludable'],
   'Person doing a morning workout in a bright modern gym, natural sunlight streaming through windows, energetic and motivating atmosphere, fitness photography',
   'seed', 'es'),

  (ind_salud, 'carousel',
   '5 hábitos matutinos respaldados por la ciencia',
   'Lo que haces en los primeros 30 minutos del día define tu energía, enfoque y bienestar.

1. Hidratación: Un vaso de agua antes del café (tu cuerpo lleva 8 horas sin agua)
2. Luz solar: 10 min de luz natural para regular tu ritmo circadiano
3. Movimiento: 5 min de estiramiento o caminata corta
4. Mindfulness: 5 min de respiración consciente o meditación
5. Nutrición: Desayuno con proteína para estabilizar la glucosa

No necesitas hacer los 5. Empieza con 1 y ve sumando.

[Descarga nuestra guía de rutina matutina]',
   ARRAY['#habitossaludables', '#bienestar', '#rutina', '#wellness', '#saludmental'],
   'Peaceful morning scene with person stretching by a window, sunrise light, yoga mat on wooden floor, green plants, serene wellness atmosphere, lifestyle photography',
   'seed', 'es'),

  (ind_salud, 'post',
   'Nutrición: lo que tu cuerpo realmente necesita',
   'Olvídate de las dietas de moda. La nutrición real es más simple de lo que crees:

→ Proteína en cada comida (no solo en el almuerzo)
→ Verduras de colores variados (cada color = nutrientes distintos)
→ Grasas saludables: palta, aceite de oliva, frutos secos
→ Carbohidratos complejos: avena, arroz integral, legumbres
→ Agua: mínimo 2 litros al día

No se trata de restricción. Se trata de darle a tu cuerpo lo que necesita para funcionar bien.

[Agenda tu evaluación nutricional]',
   ARRAY['#nutricion', '#alimentacionsaludable', '#bienestar', '#dieta', '#vidasana'],
   'Colorful healthy meal prep with fresh vegetables, fruits, grains and proteins arranged on a clean kitchen counter, top-down food photography, vibrant natural colors',
   'seed', 'es');

END $$;
