-- Migration: 006 — Content items and drafts
-- Created: 2026-05-15

-- A content item is a finalized (or in-progress) piece of content for a channel.
-- It can have multiple drafts generated by AI before being approved.

CREATE TABLE IF NOT EXISTS kefy_content_items (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id          UUID        NOT NULL REFERENCES kefy_organizations(id) ON DELETE CASCADE,
  brand_kit_id    UUID        REFERENCES kefy_brand_kits(id) ON DELETE SET NULL,
  channel         TEXT        NOT NULL
                              CHECK (channel IN ('linkedin', 'instagram', 'facebook', 'twitter', 'tiktok', 'threads', 'generic')),
  status          TEXT        NOT NULL DEFAULT 'draft'
                              CHECK (status IN ('draft', 'approved', 'scheduled', 'published', 'archived')),
  title           TEXT,
  body            TEXT,
  image_url       TEXT,
  image_prompt    TEXT,
  hashtags        TEXT[]      NOT NULL DEFAULT '{}',
  metadata        JSONB       NOT NULL DEFAULT '{}',
  created_by      UUID        REFERENCES kefy_users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS kefy_content_items_org_idx      ON kefy_content_items (org_id);
CREATE INDEX IF NOT EXISTS kefy_content_items_status_idx   ON kefy_content_items (org_id, status);
CREATE INDEX IF NOT EXISTS kefy_content_items_channel_idx  ON kefy_content_items (org_id, channel);
CREATE INDEX IF NOT EXISTS kefy_content_items_created_idx  ON kefy_content_items (org_id, created_at DESC);

CREATE TRIGGER kefy_content_items_updated_at
  BEFORE UPDATE ON kefy_content_items
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Each AI generation attempt is stored as a draft for history / undo.
CREATE TABLE IF NOT EXISTS kefy_content_drafts (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  content_item_id  UUID        NOT NULL REFERENCES kefy_content_items(id) ON DELETE CASCADE,
  org_id           UUID        NOT NULL REFERENCES kefy_organizations(id) ON DELETE CASCADE,
  body             TEXT        NOT NULL,
  model            TEXT        NOT NULL,  -- e.g. 'claude-opus-4-5', 'gpt-4o'
  prompt_used      TEXT,
  tokens_used      INTEGER,
  selected         BOOLEAN     NOT NULL DEFAULT false,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS kefy_content_drafts_item_idx ON kefy_content_drafts (content_item_id);
CREATE INDEX IF NOT EXISTS kefy_content_drafts_org_idx  ON kefy_content_drafts (org_id);
