import Mux from '@mux/mux-node';

// ─── Client singleton ─────────────────────────────────────────────────────────

let _client: Mux | null = null;

export function getMuxClient(): Mux {
  if (!_client) {
    const tokenId     = process.env.MUX_TOKEN_ID;
    const tokenSecret = process.env.MUX_TOKEN_SECRET;
    if (!tokenId || !tokenSecret) {
      throw new Error('Missing MUX_TOKEN_ID or MUX_TOKEN_SECRET env vars');
    }
    _client = new Mux({ tokenId, tokenSecret });
  }
  return _client;
}

// ─── Types ────────────────────────────────────────────────────────────────────

export interface MuxUploadResult {
  uploadId:  string;
  uploadUrl: string;  // GCS URL to PUT the video file to
}

export interface MuxAssetStatus {
  assetId:    string;
  playbackId: string | null;
  status:     'preparing' | 'ready' | 'errored';
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Create a Mux Direct Upload URL.
 * Returns an uploadId and a GCS URL to PUT the video file to.
 * After the PUT, Mux automatically creates an asset.
 */
export async function createMuxDirectUpload(): Promise<MuxUploadResult> {
  const mux = getMuxClient();
  const upload = await mux.video.uploads.create({
    cors_origin: '*',
    new_asset_settings: {
      playback_policy: ['public'],
      encoding_tier:   'baseline',  // faster processing, suitable for short reels
    },
  });

  return {
    uploadId:  upload.id ?? '',
    uploadUrl: upload.url ?? '',
  };
}

/**
 * Get the current status of a Mux upload and its created asset.
 * Returns null assetId/playbackId if not ready yet.
 */
export async function getMuxUploadStatus(uploadId: string): Promise<MuxAssetStatus & { uploadStatus: string }> {
  const mux    = getMuxClient();
  const upload = await mux.video.uploads.retrieve(uploadId);

  if (!upload.asset_id) {
    return {
      uploadStatus: upload.status,
      assetId:      '',
      playbackId:   null,
      status:       'preparing',
    };
  }

  const asset = await mux.video.assets.retrieve(upload.asset_id);
  const playbackId = asset.playback_ids?.[0]?.id ?? null;

  return {
    uploadStatus: upload.status,
    assetId:      asset.id,
    playbackId,
    status:       asset.status as 'preparing' | 'ready' | 'errored',
  };
}

/**
 * Retrieve a Mux asset by ID.
 */
export async function getMuxAsset(assetId: string): Promise<MuxAssetStatus> {
  const mux   = getMuxClient();
  const asset = await mux.video.assets.retrieve(assetId);
  const playbackId = asset.playback_ids?.[0]?.id ?? null;

  return {
    assetId:    asset.id,
    playbackId,
    status:     asset.status as 'preparing' | 'ready' | 'errored',
  };
}

/**
 * Get the Mux thumbnail URL for a given playback ID.
 * The thumbnail is auto-generated by Mux from the video.
 */
export function getMuxThumbnailUrl(playbackId: string, options?: {
  time?:   number;   // seconds into video, default 0
  width?:  number;   // px, default auto
  height?: number;
}): string {
  const params = new URLSearchParams();
  if (options?.time   != null) params.set('time',   String(options.time));
  if (options?.width  != null) params.set('width',  String(options.width));
  if (options?.height != null) params.set('height', String(options.height));
  const qs = params.toString();
  return `https://image.mux.com/${playbackId}/thumbnail.jpg${qs ? `?${qs}` : ''}`;
}

/**
 * Get the Mux animated GIF URL for a given playback ID.
 * Great for hover previews in the content list.
 */
export function getMuxAnimatedGifUrl(playbackId: string, options?: {
  fps?:   number;   // default 15
  width?: number;   // default 320
  start?: number;   // seconds
  end?:   number;
}): string {
  const params = new URLSearchParams();
  if (options?.fps   != null) params.set('fps',   String(options.fps));
  if (options?.width != null) params.set('width', String(options.width));
  if (options?.start != null) params.set('start', String(options.start));
  if (options?.end   != null) params.set('end',   String(options.end));
  const qs = params.toString();
  return `https://image.mux.com/${playbackId}/animated.gif${qs ? `?${qs}` : ''}`;
}

/**
 * Delete a Mux asset.
 */
export async function deleteMuxAsset(assetId: string): Promise<void> {
  const mux = getMuxClient();
  await mux.video.assets.delete(assetId);
}
